Add documentation for mode IDs
PGMDev/Website pull request #32
Opened 2021-01-25 03:39 UTC by CoWinkKeyDinkInc

Adds documentation for mode IDs

- Changes default output of `mode-changes` to true since a null modelist is created in PGM for destroyables with no modes.
- Explains `mode-changes` can't be used with `modes`
- Adds example with mode IDs and rearranges text explaining examples.

Currently in PGM, two or more mode changes cannot happen at the same time. I am going to check and see if this is a necessary limitation and document this if it's justified.

2021-01-25 06:32 UTC, Pablete1234 commented
monument modes still default to false @CoWinkKeyDinkInc

2021-01-25 07:11 UTC, CoWinkKeyDinkInc commented
Thanks, it was really hard to wrap my head around any unintended aspects of my pull request for backwards compatibility.

2021-02-04 18:35 UTC, Indicardo requested changes
Thanks for contributing! Once these issues are fixed, it will be merged.

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/dtc.mdx
> +          should be used. Multiple modes are seperated with a space.
separated

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/dtm.mdx
> +          should be used. Multiple modes are seperated with a space.
separated

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/monument-modes.mdx
> +    <!-- destroyables... -->
This should be an actual XML destroyable, instead of a comment

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/monument-modes.mdx
> +    <!-- destroyables are already affected by modes listed in core -->
Same here, a working code snippet should be included

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/monument-modes.mdx
> +in yellow, `> > > EASY MODE < < <`
Weird phrasing?

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/monument-modes.mdx
> +attribute is not necessary in this senario.
This bit is inconsistent with the previous example. Why does it say "ten" instead of "10"?

2021-02-04 18:35 UTC, Indicardo commented on docs/modules/objectives/monument-modes.mdx
> +attribute is not necessary in this senario.
scenario

2021-02-05 15:36 UTC, Indicardo commented
Thanks for contributing!

2021-02-05 15:36 UTC, merged