Add MCASelector to chunk pruning docs
PGMDev/Website pull request #56
Opened 2022-04-07 22:18 UTC by TheRealPear

Just a quick rough draft for adding MCASelector as an alternative method for chunk pruning. I am open to suggestions or edits on here to make it better

2022-04-08 01:51 UTC, CoWinkKeyDinkInc requested changes

2022-04-08 01:51 UTC, CoWinkKeyDinkInc commented on docs/guides/packaging/pruning-chunks.mdx
> +Start by downloading MCASelector from the [GitHub page](https://github.com/Querz/mcaselector).
This is a GitHub repository, a GitHub Page is a custom website for a project.

2022-04-08 01:51 UTC, CoWinkKeyDinkInc commented on docs/guides/packaging/pruning-chunks.mdx
> +![MCASelector Download](https://i.imgur.com/3aTpkTY.png)
I would remove this image since it's pretty large and there isn't a better more fitting equivalent to the mcedit screenshot.

2022-04-08 01:51 UTC, CoWinkKeyDinkInc commented on docs/guides/packaging/pruning-chunks.mdx
> +### 2. Select the region around the map
regions.

2022-04-08 01:51 UTC, CoWinkKeyDinkInc commented on docs/guides/packaging/pruning-chunks.mdx
> +### 3. Select the chunk in or near the map
Select the chunks in the map

2022-04-08 03:22 UTC, TheRealPear commented
Thank you for the review, it has been corrected

2022-04-10 03:17 UTC, CoWinkKeyDinkInc approved these changes

2022-04-10 03:17 UTC, CoWinkKeyDinkInc commented
LGTM 👍

2022-04-10 03:18 UTC, merged